name: Compile and Test

on:
  pull_request:
  merge_group:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '--deny warnings'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: thumbv7em-none-eabi
      - run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: thumbv7em-none-eabi
      - run: cargo clippy --no-deps -- -Dwarnings

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: thumbv7em-none-eabi
          components: rustfmt, clippy, rust-src
      - run: cargo test
  
  test-all-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: thumbv7em-none-eabi
      - run: cargo test --all-features

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: thumbv7em-none-eabi
      - run: >
          cargo build
          --target thumbv7m-none-eabi
          --all-features
          